CREATE TABLE "MEMBER" (
	"MEMBER_ID"	VARCHAR2(15)		NOT NULL,
	"MEMBER_NAME"	VARCHAR2(10)		NOT NULL,
	"MEMBER_PWD"	VARCHAR2(20)		NOT NULL,
	"MEMBER_EMAIL"	VARCHAR(20)		NOT NULL,
	"MEMBER_ADDRESS"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '영문자, 숫자, 4~15글자';

COMMENT ON COLUMN "MEMBER"."MEMBER_NAME" IS '이름';

COMMENT ON COLUMN "MEMBER"."MEMBER_PWD" IS '영어,숫자,특수기호포함 12~20글자';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '@A.COM은 따로 구현';

COMMENT ON COLUMN "MEMBER"."MEMBER_ADDRESS" IS '주소...';

CREATE TABLE "WETHERINFO" (
	"THERMO"	VARCHAR2(5)		NULL,
	"WETHER"	VARCHAR(255)		NULL
);

COMMENT ON COLUMN "WETHERINFO"."THERMO" IS '데이터 불러오기 실패 시 NULL';

CREATE TABLE "PRO_LIST" (
	"PRO_SUBJECT"	VARCHAR2(100)		NOT NULL,
	"PRO_ADDRESS"	VARCHAR2(300)		NOT NULL,
	"PRO_PARTICIPANT"	VARCHAR2(30)		NOT NULL,
	"PRO_DAY"	VARCHAR2(3)		NOT NULL,
	"PRO_MONTH"	VARCHAR2(7)		NOT NULL
);

COMMENT ON COLUMN "PRO_LIST"."PRO_SUBJECT" IS '프로그램명 한글 33자, 영문 100자 이하';

COMMENT ON COLUMN "PRO_LIST"."PRO_ADDRESS" IS '교육장주소 한글 100자 이하';

COMMENT ON COLUMN "PRO_LIST"."PRO_PARTICIPANT" IS '대상 ('초등학생', '구분없음', '성인', 
'초등1~6학년', '초등1~3학년', 
'초등4~6학년', '가족', '초등4학년 이상' 
중 선택)';

COMMENT ON COLUMN "PRO_LIST"."PRO_DAY" IS '운영요일 ('월', '화', '수', '목', '금', '토', '일', '매일' 중 선택)';

COMMENT ON COLUMN "PRO_LIST"."PRO_MONTH" IS '해당년월 ('YYYY-MM' 형식)';

CREATE TABLE "BOARD_COMMUNITY" (
	"B_C_NO"	NUMBER		NOT NULL,
	"B_C_WRITER"	VARCHAR2(15)		NOT NULL,
	"B_C_TITLE"	VARCHAR2(20)		NOT NULL,
	"B_C_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"B_C_FILE"	VARCHAR2(1000)		NULL,
	"B_C_WRITE_TIME"	TIMESTAMP		NOT NULL,
	"B_C_HIT"	NUMBER	DEFAULT 1	NOT NULL
);

COMMENT ON COLUMN "BOARD_COMMUNITY"."B_C_NO" IS '해당 글번호';

COMMENT ON COLUMN "BOARD_COMMUNITY"."B_C_WRITER" IS '작성자';

COMMENT ON COLUMN "BOARD_COMMUNITY"."B_C_TITLE" IS '글제목';

COMMENT ON COLUMN "BOARD_COMMUNITY"."B_C_CONTENT" IS '글내용';

COMMENT ON COLUMN "BOARD_COMMUNITY"."B_C_FILE" IS '파일첨부';

COMMENT ON COLUMN "BOARD_COMMUNITY"."B_C_WRITE_TIME" IS '작성일';

COMMENT ON COLUMN "BOARD_COMMUNITY"."B_C_HIT" IS '기본값 1';

CREATE TABLE "PRO_REV" (
	"PRO_REV_ID"	VARCHAR2(15)		NOT NULL,
	"PRO_REV_SUBJECT"	VARCHAR2(100)		NOT NULL,
	"PRO_REV_PHONE"	VARCHAR2(11)		NOT NULL,
	"PRO_REV_TEL"	VARCHAR2(11)		NULL,
	"PRO_REV_NUM"	NUMBER		NOT NULL,
	"PRO_PART_LEVEL"	VARCHAR2(10)		NOT NULL,
	"PRO_PART_NAME"	VARCHAR2(10)		NOT NULL,
	"PRO_PART_GEN"	CHAR(2)		NOT NULL,
	"PRO_PART_SCHOOL"	VARCHAR2(30)		NOT NULL,
	"PRO_PART_DEPT"	VARCHAR2(30)		NULL
);

COMMENT ON COLUMN "PRO_REV"."PRO_REV_ID" IS '영문자, 숫자, 4~15글자';

COMMENT ON COLUMN "PRO_REV"."PRO_REV_SUBJECT" IS '프로그램명 한글 33자, 영문 100자 이하';

COMMENT ON COLUMN "PRO_REV"."PRO_REV_PHONE" IS ''-'없이 최대 11자';

COMMENT ON COLUMN "PRO_REV"."PRO_REV_TEL" IS ''-'없이 최대 11자';

COMMENT ON COLUMN "PRO_REV"."PRO_REV_NUM" IS '1이상 입력';

COMMENT ON COLUMN "PRO_REV"."PRO_PART_LEVEL" IS ''초등(1~6)', '중등(1~6)', '고등(1~6)', 성인 중 선택';

COMMENT ON COLUMN "PRO_REV"."PRO_PART_NAME" IS '수강자명';

COMMENT ON COLUMN "PRO_REV"."PRO_PART_GEN" IS ''남', '여' 중 선택';

COMMENT ON COLUMN "PRO_REV"."PRO_PART_SCHOOL" IS '참여 학교명';

COMMENT ON COLUMN "PRO_REV"."PRO_PART_DEPT" IS '소속';

CREATE TABLE "BOARD_NOTICE" (
	"B_N_NO"	NUMBER		NOT NULL,
	"B_N_WRITER"	VARCHAR2(15)		NOT NULL,
	"B_N_TITLE"	VARCHAR2(20)		NOT NULL,
	"B_N_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"B_N_FILE"	VARCHAR2(1000)		NULL,
	"B_N_WRITE_TIME"	TIMESTAMP		NOT NULL,
	"B_N_HIT"	NUMBER	DEFAULT 1	NOT NULL
);

COMMENT ON COLUMN "BOARD_NOTICE"."B_N_NO" IS '해당 글번호';

COMMENT ON COLUMN "BOARD_NOTICE"."B_N_WRITER" IS '작성자';

COMMENT ON COLUMN "BOARD_NOTICE"."B_N_TITLE" IS '글제목';

COMMENT ON COLUMN "BOARD_NOTICE"."B_N_CONTENT" IS '글내용';

COMMENT ON COLUMN "BOARD_NOTICE"."B_N_FILE" IS '파일첨부';

COMMENT ON COLUMN "BOARD_NOTICE"."B_N_WRITE_TIME" IS '작성일';

COMMENT ON COLUMN "BOARD_NOTICE"."B_N_HIT" IS '기본값 1';

CREATE TABLE "BOARD_REPLY" (
	"B_REPLY_ID"	NUMBER		NOT NULL,
	"B_REPLY_NO"	NUMBER		NOT NULL,
	"B_REPLY_WRITER"	VARCHAR2(15)		NOT NULL,
	"B_REPLY_CONTENT"	VARCHAR2(2000)		NOT NULL,
	"B_REPLY_WRITE_TIME"	TIMESTAMP		NOT NULL,
	"B_REPLY_LEVEL"	NUMBER(2)	DEFAULT 1	NOT NULL,
	"B_REPLY_REF"	NUMBER		NULL,
	"B_REPLY_STEP"	NUMBER(3)	DEFAULT 1	NOT NULL
);

COMMENT ON COLUMN "BOARD_REPLY"."B_REPLY_ID" IS '댓글';

COMMENT ON COLUMN "BOARD_REPLY"."B_REPLY_NO" IS '해당 글번호';

COMMENT ON COLUMN "BOARD_REPLY"."B_REPLY_WRITER" IS '댓글작성자';

COMMENT ON COLUMN "BOARD_REPLY"."B_REPLY_CONTENT" IS '댓글내용';

COMMENT ON COLUMN "BOARD_REPLY"."B_REPLY_WRITE_TIME" IS '댓글작성시간';

COMMENT ON COLUMN "BOARD_REPLY"."B_REPLY_LEVEL" IS '댓글1,대댓글2,대대댓글3';

COMMENT ON COLUMN "BOARD_REPLY"."B_REPLY_REF" IS '최초댓글(B_REPLY_LEVEL:1)의번호 B_REPLY_ID';

COMMENT ON COLUMN "BOARD_REPLY"."B_REPLY_STEP" IS '최초댓글기준으로 몇번째 위치인지 나타냄';

